### PR TITLE
Remoting

### PR DESCRIPTION
**Pull request by nl78**
New remoting code.

**NEW features**
- better support for logs coming from remoted fmu.
- Ability to run multiple instances of remoting simulation at once on the same host.
- linux support (code should be portable and, hopefully, easy to maintain).
- support for -x permission for FMU (produced on Unix, which may embed executables)
- synchronization between client and server use timeout to avoid deadlocks.
- fmi2String getter and setter can support more than 1 string (experimental).
- very low overhead due to remoting. (benchmark to be done)

**Limitations**
- The TCP and WINE code is  kept as it was.
- The current implementation support fmi2 only (adding fmi3 should not be a big deal)

**Notes**
- Implementation relies on Semaphores (instead of Events on windows). On unix it uses SysV interface since POSIX one is not possible between 32/64 bits processes
- The python unzipping looses -x permission, an explicit chmod is added (see `add_remoting` and `__init__`).

Pending tasks:
- [x] Fix integration in FMPy source tree 
    - [x] (CI/CD) Compilation for Windows
    - [x] (CI/CD) Compilation for Linux : enable 32+64bits compilation
    - [x] (CI/CD) Compilation for MacOS 
    - [x] remove remoting/include subdir 
-  Ensure the new code quality
    - [x] fmi2 function for ME (CS is OK) 
    - [x] fix  pathes joining client.c for unix
    - [x] tests for Windows
    - [x] tests for MacOS (code review only)
    - [x] tests for Linux
    - [x] Fix -x permission when unzipping remoted fmu
    - [x] Update doc
- [x] Find a agreement for copyright
- Nice to have
    - [x] refactor communication.c
    - [x] Conditional compilation for semtimedop() usage when available (instead of own implementation)

### CODE REVIEW

**Comment by nl78** [comment]
Major code refactoring on remoting directory.  
- TCP and WINE code is dropped 
- Add linux and macos support.

The PR is now ready for (early) review.

**Comment by gens-rainer** [comment]
Hello Torsten, hello Mr. Laurent,

thanks a lot for your effort to improve the remoting functionality. I will review and test it with our applications from Bosch-side.

Regards,
Rainer

**Comment by nl78** [comment]
Hello,
it should work for windows.
On linux, I still face CI/CD test fail (fmi2Initialization failed). As there's very few logs, I don't know if I chose the "right" 32bits linux fmu. I have no linux box. 

Nicolas

**Comment by nl78** [comment]
I finally understood the linux issue: the server launch execv() is failling with errno=13 (Permission denied). There's two options: 

1. the -x bit is lost during the setup.py bdist_wheel. (there's some threads on forums about this topic)
2. the directory in which the fmu is temporaly uncompressed is on partition mounted with noexec flag. (it is very unlikely)

I revert to commit before adding logs for investigations.

**Comment by nl78** [comment]
Finally, the execv() is correctly done. Stdout buffering led me on the wrong track (messages from server_sm weren't captured...).

**Comment by nl78** [comment]
Linux Issue: after investigations, I'm facing the issue described here: https://sourceware.org/bugzilla/show_bug.cgi?id=17980

POSIX semaphores are not working properly across 32 and 64 process. At least, in my tests.

(sorry for the long list of commits, I will stabilize Windows code properly).

**Comment by nl78** [comment]
I finally switch to SysV Semaphores on linux. It seems to work!

**Comment by nl78** [comment]
Feel free to share feedback about this PR.

**Comment by nl78** [comment]
Original TCP Remoting code is back.

**Pull request merged**
