### PR TITLE
Create a fmpy.fmi subpackage with fewer dependencies

### PR DESCRIPTION
**Pull request by trulede**
Hi, 

This PR is still a work-in-progress. I wanted to get feedback before continuing.

The idea behind this is to package the FMI/FMU parts of FMPy into a stand alone sub-package (fmpy.fmi) so that some of the larger dependencies of FMPy can be avoided (i.e. numpy). This sub-package includes all the FMI and FMU parts necessary to load and create an instance of an existing FMU. That instance can then be controlled by a simulation environment which directly calls the FMI functions of that FMU.

To complete the PR I would need to: remove the relocated functions from the main codebase, update the imports, create a dependency between fmpy & fmpy.fmi, and then sort out the build sequence.

Thanks.

### CODE REVIEW

**Comment by t-sommer** [comment]
What exactly is the goal of removing the dependency on numpy?

**Comment by trulede** [comment]
See also conda-forge/fmpy-feedstock#11

The goal for me is to create a sub-package which represents the minimal set of FMI related functionality, such that it can be used for derived works, with as few dependencies as possible. In the code which I have moved to fmpy.fmi sub-package, numpy was used only once and could be rewritten to remove that dependency - for the fmpy.fmi package only.

The remainder of FMPy remains unchanged. A person installing FMPy should not notice any change in operation or dependencies. At least that is the intention!

**Comment by jnjaeschke** [comment]
Big **+1** for this one 👍 

We are evaluating using the "core functionalities" of fmpy (basically `fmi1/2/3.py` and `model_description.py`) as an fmi interface for a python-based simulation tool. These classes work as a very nice "boilerplate interface" to the FMUs. They are implemented beautifully and could be used as a "FMU import SDK" kind of thing.

If there was a "stripped" package which only includes those classes and not the cvode, numpy etc., it would be very helpful. Otherwise I would have to add a fork of this repo as submodule and strip away all the files I don't need. That seems "hacky". 

Hit me up if you need any help.

Cheers,
Jan

**Comment by t-sommer** [comment]
@trulede, @jnjaeschke, let me know if you're interested in discussing this use case in a quick Sykpe meeting.

**Comment by jnjaeschke** [comment]
Yes, absolutely!

**Comment by trulede** [comment]
Hi @jnjaeschke  could you discuss on my behalf with @t-sommer ... just to make it easier. We have the same problem - I don't want to be installing numpy just to use the FMI classes. Numpy is bad news 🐌 

My preference is to make a contribution to FMPy and find a packaging solution in that repo. From my research a seperate setup.py is the only way to manage this within a single repo - and I don't mind it ...

Completing the refactoring is no problem. Just let me know.

**Comment by trulede** [comment]
Alternative could be to split FMPy and host the Core FMI part in a different Git repo ... but still host them on CATIA. I suspect these two parts have very different life cycles and perhaps it's easier to manage as separate repos?

**Comment by jnjaeschke** [comment]
Thought of that to. There could be a repo which is more of a "python-based fmu import sdk" and have fmpy use this as a dependency. Then there also would be separate histories and it would be easier to identify relevant changes to the core classes. And also to fork this and make changes if necessary.
But, I don't want to step over the line here - this is Torsten's project. :) 

@trulede regarding numpy and file sizes: Numpy is huge on Windows because it includes the Intel Math kernel libraries (MKL). You can install numpy w/o mkl, using openBLAS instead. That shrinks Numpy to just a few MB. If you only use the numpy array, this should also be no problem (if you use more fancy numpy stuff, it might get slower because it does not use intel-cpu-optimized code)

Here are some links for that:
https://github.com/conda-forge/numpy-feedstock/issues/108#issuecomment-428749055
https://github.com/conda-forge/numpy-feedstock/issues/84
https://stackoverflow.com/questions/47769904/size-of-executable-using-pyinstaller-and-numpy
https://stackoverflow.com/questions/46656367/how-to-create-an-environment-in-anaconda-with-numpy-nomkl

@t-sommer @trulede Should I set up a Teams meeting for a discussion?

**Comment by t-sommer** [comment]
> @t-sommer @trulede Should I set up a Teams meeting for a discussion?

Yes, please.

**Comment by trulede** [comment]
Sorry, I have to abandon this just for the moment.

**Pull request closed without merging**
