### PR TITLE
Fix URL to Reference FMUs

### LINKED ISSUE #629: Broken URL reference to Reference FMUs breaks build process
I'm working on a nix flake for building FMPy and the build process was unable to fetch the reference FMUs which is not surprising given that he hard-coded url contains conflicting version numbers. Would be nice to get this fixed.

https://github.com/CATIA-Systems/FMPy/blob/8945636e85f09e6267b2b4ee101b99c81982530a/fmpy/modelica/__init__.py#L7

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #629

### CODE REVIEW

**Comment by dietmarw** [comment]
You forgot to update the checksum. So this will trigger errors if the checksum is checked.

**Comment by t-sommer** [comment]
```
$ wget https://github.com/modelica/Reference-FMUs/releases/download/v0.0.25/Reference-FMUs-0.0.25.zip
$ sha256sum Reference-FMUs-0.0.25.zip
62e1a89c7e05b67857e5ebb834502dc06466b04cd14065fd72b2af2e3c9aea8d  Reference-FMUs-0.0.25.zip
```

**Comment by dietmarw** [comment]
Ah I missed that you did not update to the latest version 0.0.27. Any reason for that?

**Comment by t-sommer** [comment]
For this demo the version makes no difference. The code will be moved to https://github.com/modelica/Modelica-FMI (currently private) soon.

**Pull request merged**
